const mongoose = require('mongoose')
const Schema = mongoose.Schema

const commercialSchema = new Schema({
    invoiceDate1: String,
    invoiceDate2: String,
    invoiceDate3: String,
    invoiceDate4: String,
    consignee1: String,
    consignee2: String,
    consignee3: String,
    consignee4: String,
    consignee5: String,
    consignee6: String,
    coo: String,
    cofd: String,
    marks1: String,
    marks2: String,
    marks3: String,
    marks4: String,
    marks5: String,
    no1: String,
    no2: String,
    no3: String,
    no4: String,
    no5: String,
    desc1: String,
    desc2: String,
    desc3: String,
    desc4: String,
    desc5: String,
    qty1: String,
    qty2: String,
    qty3: String,
    qty4: String,
    qty5: String,
    price1: String,
    price2: String,
    price3: String,
    price4: String,
    price5: String,
    total1: String,
    total2: String,
    total3: String,
    total4: String,
    total5: String,
    total: String,
    words: String,
    product: String,
    acid:String,
}, { timestamps: true });

module.exports = mongoose.model('Commercial', commercialSchema);
